app/main/routes.py
# coding: utf-8
import json

import dialogflow_v2 as dialogflow
from flask import render_template, Blueprint, request, redirect, url_for, flash
from flask_login import login_user, current_user, logout_user, login_required

from app import db, list_chamada
from app.main.forms import LoginForm, Intent
from app.main.utils import error_type, remover_acentos, callback, detect_intent_texts, create_intent
from app.models.models_sql_alchemy import Request, Response, Admin

main = Blueprint('main', __name__)


# TODO: ESSA PARTE VAI PERGUNTAR E TREINAR A APLICAÇÃO
@main.route('/', methods=['POST', 'GET'])
@main.route('/home')
def home():
    # GET params json.
    req = request.get_json(silent=True, force=True)
    if req and request.method == 'POST':
        if req.get("id"):
            if req.get("texto") and req.get("name"):
                request_user = Request(
                    name=req.get("name"),
                    id_user=req.get("id"),
                    text=req.get("texto"))

                db.session.add(request_user)
                db.session.commit()

                # HACK: pegar da API o retorno.
                retorno = detect_intent_texts(project_id='small-talk-c36ba', session_id=request_user.id_user,
                                              texts=request_user.text, language_code='pt-br')

                response = Response(
                    action=retorno.get('action'),
                    intentDetectionConfidence=retorno.get('intentDetectionConfidence'),
                    fulfillmentText=retorno.get('fulfillmentText'),
                    parent_id=request_user.id_request
                )

                db.session.add(response)
                db.session.commit()

                return json.dumps({
                    "action": response.action,
                    "response": response.fulfillmentText
                }, indent=4, ensure_ascii=False).encode("utf8")
            else:
                return json.dumps(
                    error_type(error="Não foi encontrado Nome e Texto", session=req.get("session")),
                    ensure_ascii=False).encode('utf8')
        else:
            return json.dumps(error_type(error="Não foi informado uma Id", session='')).encode('utf8')
    else:
        return redirect(url_for('main.gerenciamento'))


@main.route('/gerenciamento', methods=["POST", "GET"])
@main.route('/admin', methods=["POST", "GET"])
@login_required
def gerenciamento():
    return render_template('home.html', title="::admin::",
                           list_all=Request.query.all()), 200


@main.route('/login', methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        if form.email.data == "admin@gmail.com" and (form.password.data == "root" or form.password.data == "123"):
            # IDEA: mudar para uma coisa mais segura
            admin = Admin.query.filter_by(email=form.email.data).first()
            login_user(admin)
            flash("Você foi logado com sucesso", "success")
            return redirect(url_for('main.home'))
        else:
            flash("Nao foi possivel logar. Por favor entre em contato com o administrador do sistema", "danger")
    return render_template('login.html', title="Login", form=form)


@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.gerenciamento'))


@main.route('/reset')
def reset():
    db.drop_all()
    db.create_all()
    admin = Admin(email="admin@gmail.com", password="root")
    db.session.add(admin)
    db.session.commit()
    flash("O Banco foi resetado com sucesso", "success")
    return redirect(url_for('main.gerenciamento'))


@main.route("/<int:request_id>/validar")
def validar(request_id):
    request_s = Request.query.get(request_id)
    if request_s:
        resposta = request_s.response[0].fulfillmentText
        list_chamada.update({str(request_id): remover_acentos(resposta)})
        flash(json.dumps(list_chamada, ensure_ascii=False).encode("utf8"), "warning")
        # return json.dumps(list_chamada, ensure_ascii=False).encode("utf8")
        return redirect(url_for('main.home'))
    else:
        return print('not ok')


@main.route("/<int:request_id>/create_intent", methods=['GET', 'POST'])
def create_intent_route(request_id):
    request_s = Request.query.get_or_404(request_id)
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form_request = Intent()
    if form_request.validate_on_submit():
        create_intent(project_id='small-talk-c36ba', display_name=form_request.name.data,
                      training_phrases_parts=form_request.response.data, message_texts=form_request.response.data)
        return redirect(url_for('main.home'))
    else:
        form_request.name.data = request_s.response[0].action
        form = form_request.response
        form.append_entry(request_s.response[0].fulfillmentText)
    return render_template('new.html', title='Criar uma nova Inteção', form=form_request)


@main.route("/<int:request_id>/delete")
def delete(request_id):
    request_user = Request.query.get_or_404(request_id)
    db.session.delete(request_user)
    db.session.commit()
    flash(" O Banco foi atualizado com a nova validação", 'success')
    return redirect(url_for('main.home'))


@main.route('/trainAgent')
def train():
    print('--' * 10)
    print('Foi adicionado ao treinamento')
    client = dialogflow.AgentsClient()
    parent = client.project_path('small-talk-c36ba')
    try:
        print(list_chamada)
        response = client.train_agent(parent=parent, metadata=list_chamada.items())
        response.add_done_callback(callback)
    except Exception as error:
        print(error)
    return redirect(url_for('main.gerenciamento'))

app/templates/home.html
{% extends "layout.html" %}

{% block content %}

{% if list_all %}
{% for request in list_all %}
<div class="row">
    <div class="col-md-6" id="request">
        <blockquote class="blockquote text-left">
            <div class="row">
                <div class="col-md-6">
                    <p><span class="text-Request">ID: </span>{{ request.id_user }}</p>
                    <p><span class="text-Request">Name:</span> {{ request.name }}</p>
                </div>
                <div class="col-md-6"><p class="article-content"><span class="text-Request">Requisição: </span>{{
                    request.text }}</p></div>
            </div>
            <footer class="blockquote-footer">Timestamp <cite>{{ request.timestamp.strftime('%Y/%m/%d - %H:%M:%S')
                }}</cite></footer>
        </blockquote>
    </div>
    <div class="col-md-5" id="response">
        <blockquote class="blockquote text-right">
            <div class="row">
                <div class="col-md-3">
                    <span><span class="text-Response">Resposta: </span></span>
                </div>
                <div class="col-md-9"><p class="article-content text-center">{{ request.response[0].fulfillmentText }}</p></div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <span><span class="text-Response">Ação: </span></span>
                </div>
                <div class="col-md-9"><p class="article-content text-muted text-left">{{ request.response[0].action }}</p></div>
            </div>
            <footer class="blockquote-footer">Timestamp <cite>{{ request.timestamp.strftime('%Y/%m/%d - %H:%M:%S')
                }}</cite></footer>
        </blockquote>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <a href="{{ url_for('main.create_intent_route', request_id = request.id_request) }}">
            <button type="button" class="btn btn-rosa-mais-escuro">Criar uma Intenção</button>
        </a>
        <a href="{{ url_for('main.validar', request_id = request.id_request) }}">
            <button type="button" class="btn btn-rosa-escuro">Validar</button>
        </a>
        <a href="{{ url_for('main.delete', request_id = request.id_request) }}">
            <button type="button" class="btn btn-rosa-claro">Cancelar</button>
        </a>
    </div>
</div>
<hr>
{% endfor %}
{% else %}
<div class="container NaoCadastrado">
    <div class="row">
        <div class="col-md-12 text-center">
            <img src="{{ url_for('static', filename='img/vikiRobot.png' ) }}" alt="Viki Robot">
        </div>
    </div>
    <div class="row">
        <p>Não foi cadastrado nenhuma requisição ainda. Entre novamente quando houver requisições ou entre com
            administrador do sistema.</p>
    </div>
</div>
{% endif %}

{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
    {% if title %}
    <title>{{ title }} </title>
    {% else %}
    <title>Página não Encontrada</title>
    {% endif %}
</head>

<body>
<header role="navigation">
    <nav class="navbar navbar-dark bg-dark">
        {% if title %}
        <a class="navbar-brand" href="{{ url_for('main.home')}}"><h3>{{title}}</h3></a>
        {% else %}
        <a class="navbar-brand" href="{{ url_for('main.home')}}"><h3>Página não Econtrada</h3></a>
        {% endif %}

        {% if current_user.is_authenticated %}
        <div class="mr-sm-2">
            <a href="{{ url_for('main.train') }}">
                <button type="button" class="btn btn-exit">Train Agent</button>
            </a>
            <a href="{{ url_for('main.logout') }}">
                <button type="button" class="btn btn-exit">Exit</button>
            </a>
        </div>

        {% endif %}
    </nav>
</header>
<main role="main" class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content%}
    {% endblock content%}
</main>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-rosa-escuro", style="width: 100%; margin: 0") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/new.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <div class="media-body">
        <form method="post" action="">
            <div class="row">
                <div class="col-md-12" id="response">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">{{ legend }}</legend>
                        <div class="form-group">
                            <span class="text-rosa-claro"><strong>{{ form.name.label(class="form-control-label") }}</strong></span>
                            <!-- valor de erro -->
                            {% if form.name.errors %}
                            {{ form.name(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.name(class="form-control text-rosa-claro form-control-lg") }}
                            {% endif %}
                        </div>
                         <div class="form-group">
                             <span class="text-rosa-claro"><strong>{{ form.response.label(class="form-control-label") }}</strong></span>
                            <!-- valor de erro -->
                            {% if form.response.errors %}
                            {{ form.response(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                <!-- adicionando lista de valores para o formulário em especifico -->
                                {% for error in form.response.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                             {% for texto in form.response %}
                                {{ texto(class="form-control text-rosa-claro form-control-lg") }}
                             {% endfor %}

                            {% endif %}
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        {{ form.submit(class="btn btn-rosa-escuro") }}
                    </div>
                </div>
            </div>
        </form>
    </div>

</article>
{% endblock content %}